{
  "openapi": "3.0.0",
  "info": {
    "title": "API for bookstore",
    "description": "RESTs Api for Mobile app",
    "version": "1.0.0"
  },
  "servers": [
    {
      "url": "http://localhost:5001/api/v1",
      "description": "Local server"
    }
  ],
  "paths": {
    "/users": {
      "get": {
        "tags": [
          "User"
        ],
        "description": "Get all users",
        "parameters": [],
        "responses": {
          "200": {
            "description": "Get all users success",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/AllUsers"
                }
              }
            }
          },
          "500": {
            "description": "Sign up fail",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Response"
                },
                "examples": {
                  "ServerError": {
                    "$ref": "#/components/examples/ServerErrorResponse"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/users/signup": {
      "post": {
        "tags": [
          "User"
        ],
        "description": "Create new user",
        "parameters": [],
        "responses": {
          "201": {
            "description": "Sign up success",
            "content": {
              "application/json": {
                "schema": {
                  "allOf": [
                    {
                      "$ref": "#/components/schemas/Response"
                    },
                    {
                      "type": "object",
                      "properties": {
                        "data": {
                          "$ref": "#/components/schemas/User"
                        }
                      }
                    }
                  ]
                },
                "examples": {
                  "CreatedUserResponse": {
                    "$ref": "#/components/examples/CreatedUserResponse"
                  }
                }
              }
            }
          },
          "500": {
            "description": "Sign up fail",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Response"
                },
                "examples": {
                  "ServerError": {
                    "$ref": "#/components/examples/ServerErrorResponse"
                  }
                }
              }
            }
          }
        },
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/UserRegister"
              }
            },
            "application/xml": {
              "schema": {
                "$ref": "#/components/schemas/UserRegister"
              }
            }
          }
        }
      }
    },
    "/users/signin": {
      "post": {
        "tags": [
          "User"
        ],
        "description": "Sign in user",
        "parameters": [],
        "responses": {
          "200": {
            "description": "Sign in success",
            "content": {
              "application/json": {
                "schema": {
                  "allOf": [
                    {
                      "$ref": "#/components/schemas/Response"
                    },
                    {
                      "type": "object",
                      "properties": {
                        "data": {
                          "$ref": "#/components/schemas/User"
                        }
                      }
                    }
                  ]
                },
                "examples": {
                  "CreatedUserResponse": {
                    "$ref": "#/components/examples/SignInSuccessResponse"
                  }
                }
              }
            }
          },
          "500": {
            "description": "Sign up fail",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Response"
                },
                "examples": {
                  "ServerError": {
                    "$ref": "#/components/examples/ServerErrorResponse"
                  }
                }
              }
            }
          }
        },
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/UserLogin"
              }
            },
            "application/xml": {
              "schema": {
                "$ref": "#/components/schemas/UserLogin"
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "securitySchemas": {
      "bearerAuth": {
        "type": "http",
        "scheme": "bearer",
        "bearerFormat": "JWT"
      }
    },
    "examples": {
      "CreatedUserResponse": {
        "value": {
          "success": true,
          "data": {
            "id": 1,
            "firstName": "John",
            "lastName": "Doe",
            "email": "hualocson@gmail.com",
            "phone": "09876543219",
            "avatar": "https://i.imgur.com/1J2h7Yt.jpg"
          },
          "message": "Request successful!",
          "statusCode": 201
        }
      },
      "SignInSuccessResponse": {
        "value": {
          "success": true,
          "data": {
            "id": 1,
            "firstName": "John",
            "lastName": "Doe",
            "email": "hualocson@gmail.com",
            "phone": "09876543219",
            "avatar": "https://i.imgur.com/1J2h7Yt.jpg"
          },
          "message": "Request successful!",
          "statusCode": 200
        }
      },
      "ServerErrorResponse": {
        "value": {
          "success": false,
          "data": null,
          "message": "Request failed!",
          "statusCode": 500
        }
      }
    },
    "schemas": {
      "User": {
        "type": "object",
        "properties": {
          "id": {
            "type": "integer",
            "example": 1
          },
          "firstName": {
            "type": "string",
            "example": "John"
          },
          "lastName": {
            "type": "string",
            "example": "Doe"
          },
          "email": {
            "type": "string",
            "example": "email@gmail.com"
          },
          "password": {
            "type": "string",
            "example": "123456"
          },
          "phone": {
            "type": "string",
            "example": "09876543219"
          },
          "avatar": {
            "type": "string",
            "example": "https://i.imgur.com/1J2h7Yt.jpg"
          }
        }
      },
      "UserLogin": {
        "type": "object",
        "properties": {
          "email": {
            "type": "string",
            "example": "email@gmail.com"
          },
          "password": {
            "type": "string",
            "example": "123456"
          }
        }
      },
      "UserRegister": {
        "type": "object",
        "properties": {
          "firstName": {
            "type": "string",
            "example": "John"
          },
          "lastName": {
            "type": "string",
            "example": "Doe"
          },
          "email": {
            "type": "string",
            "example": "email@gmail.com"
          },
          "password": {
            "type": "string",
            "example": "123456"
          },
          "phone": {
            "type": "string",
            "example": "09876543219"
          },
          "avatar": {
            "type": "string",
            "example": "https://i.imgur.com/1J2h7Yt.jpg"
          }
        }
      },
      "AllUsers": {
        "type": "array",
        "items": {
          "$ref": "#/components/schemas/User"
        }
      },
      "Response": {
        "type": "object",
        "properties": {
          "success": {
            "type": "boolean"
          },
          "data": {
            "type": "object"
          },
          "message": {
            "type": "string"
          },
          "statusCode": {
            "type": "integer"
          }
        }
      }
    }
  },
  "security": [
    {
      "bearerAuth": []
    }
  ]
}